In [1]:
import numpy as np

In [2]:
l = [3,4,5,3]
print(l)
print(type(l))

arr = np.array([3,5,6,3])
print(arr)
print(type(arr))


[3, 4, 5, 3]
<class 'list'>
[3 5 6 3]
<class 'numpy.ndarray'>


#### creating NumPy array

In [3]:
list = [3,5,6,3,2] # list

# 1 method
arr = np.array(list) # creating array using array() fun.
print(arr)

[3 5 6 3 2]


In [4]:
#2 method
arr = np.array([2,4,5,3,3])
print(arr)

[2 4 5 3 3]


#### 2D array

In [5]:
# 2D array 

list1 = [3,3,5,2,3]
list2 = [3,5,2,1,3]

arr = np.array([(list1), (list2)])
print(arr)

print(arr.ndim)
print()

[[3 3 5 2 3]
 [3 5 2 1 3]]
2



In [6]:
# l = [] # empty list
# for i in range(1,6):
#     val = int(input(f"Enter value at index {i} : "))
#     l.append(val)

# arr = np.array(l)
# print(arr)
# print("Diamention : ", np.ndim(arr)) # 1 method
# print("Diamention : ", arr.ndim) # 2 mehtod

#### 3D array

In [7]:
arr = np.array([[[2,4],[3,2]]])
print(arr)
print("Diametion is : ", arr.ndim)

[[[2 4]
  [3 2]]]
Diametion is :  3


N Diametion Array

In [8]:
arr = np.array([3,4,2,4,2,6],ndmin=10)
print(arr)
print("Diametion is : ", arr.ndim)

[[[[[[[[[[3 4 2 4 2 6]]]]]]]]]]
Diametion is :  10


Create the NumPy array using Function

In [9]:
arr = np.zeros((3,4)) # zeros() function

# arr = np.zeros((3,4),dtype=int)  # another type convert data type of array
print(arr)

#converting array float to intger
print(arr.astype(int))

print("converte array into n diamention")
high_D_Arr = np.array(arr,ndmin=10)
print(high_D_Arr)
print("Diamention is : ", high_D_Arr.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
converte array into n diamention
[[[[[[[[[[0. 0. 0. 0.]
         [0. 0. 0. 0.]
         [0. 0. 0. 0.]]]]]]]]]]
Diamention is :  10


In [10]:
# ones() function
arr = np.ones((3,5),dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
# empty() function

arr = np.empty((2,3), dtype=int)
print(arr)
print(arr.ndim)

[[3 4 2]
 [4 2 6]]
2


In [12]:
arr = np.empty((2,3))
print(arr)

arr.fill(7) # fill() function modify the array by the given argument

print(arr.astype(int))
print(arr.shape)

[[4.45057637e-308 8.90104239e-307 1.11255866e-306]
 [1.33511561e-306 1.11261027e-306 4.94065646e-322]]
[[7 7 7]
 [7 7 7]]
(2, 3)


In [13]:
# arange() fun.
arr = np.arange(3,10)
# arr = np.array(arr,ndmin=4) # converting into 4D
print(arr.shape)
print(arr)
print("Diamention is : ", arr.ndim)

(7,)
[3 4 5 6 7 8 9]
Diamention is :  1


In [14]:
# eye() fun. create the identiy metrices

arr = np.eye(4,dtype=int)
# arr.astype(int)
# arr = np.array(arr,ndmin=10)
print(arr)
print(arr.shape)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
(4, 4)


In [15]:
arr = np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [16]:
#linspace()

arr, step = np.linspace(0,20,num=5,retstep=True,dtype=int)
print(arr)
print(step)

[ 0  5 10 15 20]
5.0


Create array with the Random number 

In [17]:
# rand(row,col)
arr = np.random.rand(3,4) # generate the values b/w 0 & 1
print(arr.ndim)
print(arr)

2
[[0.10478737 0.0120317  0.689515   0.86495544]
 [0.67374828 0.00488869 0.48621317 0.8201306 ]
 [0.54405842 0.5868812  0.69342714 0.78669206]]


In [18]:
# randint(start, end, total_no.)
arr = np.random.randint(1,10,(3,4)) # generate 1 to 9, 3X4 metices
print(arr)

[[7 5 5 7]
 [6 6 7 1]
 [1 2 9 9]]


In [19]:
# randn(row,col)
arr = np.random.randn(3,4) # generate the no. close to 0 -ve & +ve both
print(arr)

[[ 0.03957107 -0.36199437  1.50408645  0.49038709]
 [ 0.70462334  2.47705855  0.59333827  1.47118678]
 [-0.93172255  0.91764977  0.90912214 -0.78880882]]


In [20]:
# ranf(row, col)
arr = np.random.ranf(4) # [0.0 to 1.0) generate the no. 0 to 1 (not include 1)
# print(arr.reshape(2,2))
print(arr)

[0.30971239 0.26789471 0.91009969 0.45004621]


DATA TYPES 

In [21]:
arr = np.array([3,4,2,6])
print(arr.dtype)

int64


In [22]:
#float
arr = np.array([3.5,2.0,3.5,6.3])
print(arr.dtype)

float64


In [23]:
# string 
arr = np.array(['A','D','F','G'])
print(arr.dtype)

<U1


In [24]:
#string & integer

arr = np.array(["A","F","C",2,3,5])
print(arr.dtype)

<U21


In [25]:
#boolean

arr = np.array([True, False, True])
print(arr.dtype)

bool


change the data type of an array

In [26]:
arr = np.array([1,4,6,3,4],dtype=str)
print(arr)
arr = np.array([1,4,6,3,4],dtype=float)
print(arr)
arr = np.array([1,4,6,3,4],dtype=bool)
print(arr)
arr = np.array(["1","4","6","3","4"],dtype=int)
print(arr)
arr = np.array(["1","4","6","3","4"],dtype=float)
print(arr)


['1' '4' '6' '3' '4']
[1. 4. 6. 3. 4.]
[ True  True  True  True  True]
[1 4 6 3 4]
[1. 4. 6. 3. 4.]


In [27]:
arr = np.array([1,2,4,3],dtype=np.int8)
print(arr.dtype)

# another way
arr = np.array([3,4,5,2],dtype="f")
print(arr.dtype)

int8
float32


In [28]:
arr = np.array([3,6,7,4])

new = np.float64(arr)
print(arr.dtype)
print(arr)
print(new.dtype)
print(new)

new1 = np.int_(new)
print(arr.dtype)
print(new1)

int64
[3 6 7 4]
float64
[3. 6. 7. 4.]
int64
[3 6 7 4]


In [29]:
arr = np.array([3,5,2,4,5])
new = arr.astype(float)
print(arr)
print(new)

[3 5 2 4 5]
[3. 5. 2. 4. 5.]


Shape & Reshape in NumPy array

In [30]:
arr = np.array([[2,5,3],[2,5,5]])
print(arr.shape)

(2, 3)


In [31]:
# change diametions

arr = np.array([2,5,67,3],ndmin=4)
print(arr.ndim)

4


In [32]:
arr = np.array([1,2,3,4,5,6])
print(arr)
new = arr.reshape(2,3)
print("\n" ,new)

[1 2 3 4 5 6]

 [[1 2 3]
 [4 5 6]]


In [33]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new = arr.reshape(3,2,2) # reshape(bock,row,col)
print(new)
print(new.ndim)


#convert into 1D array

_1D = new.reshape(-1) # -1 convert into 1D array
print(_1D)
print(_1D.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


Arithmetics operations in NumPy Array

In [34]:
arr = np.array([[2,3,5,6],[3,4,1,3]])
arr = np.array([[2,3,5,6],[3,4,1,3]])

add = arr 
print(add)

[[2 3 5 6]
 [3 4 1 3]]
